// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TurnosAPI.Models;

#nullable disable

namespace TurnosAPI.Migrations
{
    [DbContext(typeof(turnos2024Context))]
    [Migration("20241005032428_BorradoLogico")]
    partial class BorradoLogico
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TurnosAPI.Models.TDetallesTurno", b =>
                {
                    b.Property<int>("IdTurno")
                        .HasColumnType("int")
                        .HasColumnName("id_turno");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int")
                        .HasColumnName("id_servicio");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdTurno", "IdServicio");

                    b.HasIndex("IdServicio");

                    b.ToTable("T_DETALLES_TURNO", (string)null);
                });

            modelBuilder.Entity("TurnosAPI.Models.TServicio", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Borrado")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("bit")
                        .HasColumnName("borrado");

                    b.Property<int>("Costo")
                        .HasColumnType("int")
                        .HasColumnName("costo");

                    b.Property<string>("EnPromocion")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("enPromocion");

                    b.Property<string>("Motivo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("motivoBorrado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("T_SERVICIOS", (string)null);
                });

            modelBuilder.Entity("TurnosAPI.Models.TTurno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cliente")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("cliente");

                    b.Property<string>("Fecha")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("fecha");

                    b.Property<string>("Hora")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("hora");

                    b.HasKey("Id");

                    b.ToTable("T_TURNOS", (string)null);
                });

            modelBuilder.Entity("TurnosAPI.Models.TDetallesTurno", b =>
                {
                    b.HasOne("TurnosAPI.Models.TServicio", "IdServicioNavigation")
                        .WithMany("TDetallesTurnos")
                        .HasForeignKey("IdServicio")
                        .IsRequired()
                        .HasConstraintName("FK_DETALLES_TURNO_SERVICIOS");

                    b.HasOne("TurnosAPI.Models.TTurno", "IdTurnoNavigation")
                        .WithMany("TDetallesTurnos")
                        .HasForeignKey("IdTurno")
                        .IsRequired()
                        .HasConstraintName("FK_DETALLES_TURNO_TURNOS");

                    b.Navigation("IdServicioNavigation");

                    b.Navigation("IdTurnoNavigation");
                });

            modelBuilder.Entity("TurnosAPI.Models.TServicio", b =>
                {
                    b.Navigation("TDetallesTurnos");
                });

            modelBuilder.Entity("TurnosAPI.Models.TTurno", b =>
                {
                    b.Navigation("TDetallesTurnos");
                });
#pragma warning restore 612, 618
        }
    }
}
